# modified from https://github.com/PAPAMICA/docker-environment
version: '3.3'
services:
    traefik:
        image: traefik:latest
        container_name: ${SERVICE}
        restart: always
        healthcheck:
          test: grep -qr "traefik" /proc/*/status || exit 1
          interval: 1m
          timeout: 30s
          retries: 3
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ${DATA_LOCATION}/${SERVICE}/config/traefik.yml:/traefik.yml:ro
            - ${DATA_LOCATION}/${SERVICE}/config/config.yml:/config.yml:ro  
            - ${DATA_LOCATION}/${SERVICE}/config/acme.json:/acme.json
            - ${DATA_LOCATION}/${SERVICE}/config/custom:/custom:ro
        labels:
          # Front API
          autoupdate: monitor
          traefik.enable: true
          traefik.http.routers.api.entrypoints: https
          traefik.http.routers.api.rule: Host("${SERVICE}.${DOMAIN}")
          traefik.http.routers.api.service: api@internal
          traefik.http.routers.api.middlewares: auth
          traefik.http.middlewares.auth.basicauth.users: ${USERPASS}
        networks:
            - ${NETWORK}

networks:
    proxy:
        external:
            name: ${NETWORK}